services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "4000:4000"

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8000:8000"

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
